# Documentation: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsuses
name: integrity-checker_workflow
run-name: integrity-checker workflow

# Allow one concurrent deployment
concurrency:
  group: "integrity-checker"
  cancel-in-progress: true

on:
  push:
    branches:
      - main
      - prod

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  review:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Lint Python app
        uses: ./.github/actions/lint-python-app
        with:
          python-app-path: .

  test:
    needs: review
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Test Python app
        uses: ./.github/actions/test-python-app
        with:
          python-app-path: .
          token: ${{ secrets.GITHUB_TOKEN }}

  release:
    needs: test
    runs-on: ubuntu-latest
    # Only run on main
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Build and push Docker image to GitHub
        id: build-and-push-docker-image-to-github
        uses: ./.github/actions/build-and-push-docker-image-to-github
        with:
          docker-registry-username: ${{ github.actor }}
          docker-registry-password: ${{ secrets.GITHUB_TOKEN }}
          docker-image-name: swiss-ai-center/integrity-checker
          docker-image-context: .
    outputs:
      docker-image-tags: ${{ steps.build-and-push-docker-image-to-github.outputs.docker-image-tags }}

  deploy-dev:
    needs: release
    runs-on: ubuntu-latest
    # Only run on main
    if: success() && github.ref == 'refs/heads/main'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Prepare configuration files
        shell: bash
        working-directory: ./kubernetes
        env:
          ENVIRONMENT: production
          LOG_LEVEL: info
          ENGINE_URLS: "'[\"https://backend-core-engine-swiss-ai-center.kube.isc.heia-fr.ch\"]'"
          SERVICE_URL: https://integrity-checker-swiss-ai-center.kube.isc.heia-fr.ch
        run: |
          # Set integrity-checker version
          docker_image_tags=(${{ needs.release.outputs.docker-image-tags }})
          docker_image_sha_tag="${docker_image_tags[1]}"
          yq ".spec.template.spec.containers[0].image = \"$docker_image_sha_tag\"" integrity-checker.stateful.yml > new-integrity-checker.stateful.yml && mv new-integrity-checker.stateful.yml integrity-checker.stateful.yml

          # Set integrity-checker configuration (ConfigMap)
          yq '.data = (.data | to_entries | map({"key": .key, "value": "${" + .key + "}"}) | from_entries)' integrity-checker.config-map.yml | envsubst > new-integrity-checker.config-map.yml && mv new-integrity-checker.config-map.yml integrity-checker.config-map.yml

          # Set integrity-checker configuration (Ingress)
          yq ".spec.rules[0].host = \"${SERVICE_URL#*://}\"" integrity-checker.ingress.yml > new-integrity-checker.ingress.yml && mv new-integrity-checker.ingress.yml integrity-checker.ingress.yml
          yq ".spec.tls[0].hosts[0] = \"${SERVICE_URL#*://}\"" integrity-checker.ingress.yml > new-integrity-checker.ingress.yml && mv new-integrity-checker.ingress.yml integrity-checker.ingress.yml

      - name: Deploy integrity-checker on the Kubernetes cluster
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG_DEV }}
          kube-namespace: swiss-ai-center-dev
          kubectl-context: ./kubernetes
          kubectl-args: |
            apply \
              -f integrity-checker.config-map.yml \
              -f integrity-checker.stateful.yml \
              -f integrity-checker.service.yml \
              -f integrity-checker.ingress.yml

  deploy-prod:
    needs: release
    runs-on: ubuntu-latest
    # Only run on prod
    if: success() && github.ref == 'refs/heads/prod'
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Prepare configuration files
        shell: bash
        working-directory: ./kubernetes
        env:
          ENVIRONMENT: production
          LOG_LEVEL: info
          ENGINE_URLS: "'[\"https://backend-core-engine-swiss-ai-center.kube.isc.heia-fr.ch\"]'"
          SERVICE_URL: https://integrity-checker-swiss-ai-center.kube.isc.heia-fr.ch
        run: |
          # Set integrity-checker version
          docker_image_tags=(${{ needs.release.outputs.docker-image-tags }})
          docker_image_sha_tag="${docker_image_tags[1]}"
          yq ".spec.template.spec.containers[0].image = \"$docker_image_sha_tag\"" integrity-checker.stateful.yml > new-integrity-checker.stateful.yml && mv new-integrity-checker.stateful.yml integrity-checker.stateful.yml

          # Set integrity-checker configuration (ConfigMap)
          yq '.data = (.data | to_entries | map({"key": .key, "value": "${" + .key + "}"}) | from_entries)' integrity-checker.config-map.yml | envsubst > new-integrity-checker.config-map.yml && mv new-integrity-checker.config-map.yml integrity-checker.config-map.yml

          # Set integrity-checker configuration (Ingress)
          yq ".spec.rules[0].host = \"${SERVICE_URL#*://}\"" integrity-checker.ingress.yml > new-integrity-checker.ingress.yml && mv new-integrity-checker.ingress.yml integrity-checker.ingress.yml
          yq ".spec.tls[0].hosts[0] = \"${SERVICE_URL#*://}\"" integrity-checker.ingress.yml > new-integrity-checker.ingress.yml && mv new-integrity-checker.ingress.yml integrity-checker.ingress.yml

      - name: Deploy integrity-checker on the Kubernetes cluster
        uses: ./.github/actions/execute-command-on-kubernetes-cluster
        with:
          kube-config: ${{ secrets.KUBE_CONFIG_PROD }}
          kube-namespace: swiss-ai-center-prod
          kubectl-context: ./kubernetes
          kubectl-args: |
            apply \
              -f integrity-checker.config-map.yml \
              -f integrity-checker.stateful.yml \
              -f integrity-checker.service.yml \
              -f integrity-checker.ingress.yml